
CREATE TABLE IF NOT EXISTS REBELDE (
    ID UUID PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    IDADE int4 NULL,
    GENERO CHAR(1)
);
CREATE TABLE IF NOT EXISTS LOCALIZACAO(
    ID uuid PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    LATITUDE numeric(16),
    LONGITUDE NUMERIC(16),
    FOREIGN KEY (ID) REFERENCES REBELDE (ID)

);

CREATE TABLE IF NOT EXISTS INVENTARIO(
    ID UUID PRIMARY KEY NOT NULL,
    ARMA NUMERIC (10, 0),
    MUNICAO NUMERIC (10, 0),
    AGUA NUMERIC (10, 0),
    COMIDA NUMERIC (10, 0),
    FOREIGN KEY (ID) references  REBELDE (ID)
);